<!-- jQuery依赖 -->
<script type="text/javascript" src="/assets/js/jquery.js"></script>
<!-- 日期处理依赖 -->
<script type="text/javascript" src="/assets/js/moment.js"></script>
<!-- Bootstrap依赖 -->
<script type="text/javascript" src="/assets/js/bootstrap.js"></script>
<!-- Angular外部依赖 -->
<script type="text/javascript" src="/assets/js/angular-dep.js"></script>
<!-- Angular核心依赖 -->
<script type="text/javascript" src="/assets/js/angular.js"></script>
<!-- Angular插件依赖 -->
<script type="text/javascript" src="/assets/js/angular-extra.js"></script>
<!-- 其他通用插件依赖 -->
<script type="text/javascript" src="/assets/js/plugins.js"></script>
<!-- 项目需要依赖 -->
<script type="text/javascript" src="/assets/js/vendor.js"></script>